/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as LoginForgotPasswordIndexImport } from './routes/login/forgot-password/index'
import { Route as AssessmentExaminationIndexImport } from './routes/assessment/examination/index'

// Create/Update Routes

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const LoginForgotPasswordIndexRoute = LoginForgotPasswordIndexImport.update({
  id: '/login/forgot-password/',
  path: '/login/forgot-password/',
  getParentRoute: () => rootRoute,
} as any)

const AssessmentExaminationIndexRoute = AssessmentExaminationIndexImport.update(
  {
    id: '/assessment/examination/',
    path: '/assessment/examination/',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/assessment/examination/': {
      id: '/assessment/examination/'
      path: '/assessment/examination'
      fullPath: '/assessment/examination'
      preLoaderRoute: typeof AssessmentExaminationIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/forgot-password/': {
      id: '/login/forgot-password/'
      path: '/login/forgot-password'
      fullPath: '/login/forgot-password'
      preLoaderRoute: typeof LoginForgotPasswordIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/assessment/examination': typeof AssessmentExaminationIndexRoute
  '/login/forgot-password': typeof LoginForgotPasswordIndexRoute
}

export interface FileRoutesByTo {
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/assessment/examination': typeof AssessmentExaminationIndexRoute
  '/login/forgot-password': typeof LoginForgotPasswordIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/assessment/examination/': typeof AssessmentExaminationIndexRoute
  '/login/forgot-password/': typeof LoginForgotPasswordIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/assessment/examination'
    | '/login/forgot-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/assessment/examination'
    | '/login/forgot-password'
  id:
    | '__root__'
    | '/dashboard/'
    | '/login/'
    | '/assessment/examination/'
    | '/login/forgot-password/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  AssessmentExaminationIndexRoute: typeof AssessmentExaminationIndexRoute
  LoginForgotPasswordIndexRoute: typeof LoginForgotPasswordIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  AssessmentExaminationIndexRoute: AssessmentExaminationIndexRoute,
  LoginForgotPasswordIndexRoute: LoginForgotPasswordIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard/",
        "/login/",
        "/assessment/examination/",
        "/login/forgot-password/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/assessment/examination/": {
      "filePath": "assessment/examination/index.tsx"
    },
    "/login/forgot-password/": {
      "filePath": "login/forgot-password/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
