/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StudentsIndexImport } from './routes/students/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as StudentsStudentsListIndexImport } from './routes/students/students-list/index'
import { Route as LoginForgotPasswordIndexImport } from './routes/login/forgot-password/index'
import { Route as AssessmentTestsIndexImport } from './routes/assessment/tests/index'
import { Route as AssessmentQuestionPapersIndexImport } from './routes/assessment/question-papers/index'
import { Route as AssessmentTestsCreateAssessmentIndexImport } from './routes/assessment/tests/create-assessment/index'

// Create/Update Routes

const StudentsIndexRoute = StudentsIndexImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const StudentsStudentsListIndexRoute = StudentsStudentsListIndexImport.update({
  id: '/students/students-list/',
  path: '/students/students-list/',
  getParentRoute: () => rootRoute,
} as any)

const LoginForgotPasswordIndexRoute = LoginForgotPasswordIndexImport.update({
  id: '/login/forgot-password/',
  path: '/login/forgot-password/',
  getParentRoute: () => rootRoute,
} as any)

const AssessmentTestsIndexRoute = AssessmentTestsIndexImport.update({
  id: '/assessment/tests/',
  path: '/assessment/tests/',
  getParentRoute: () => rootRoute,
} as any)

const AssessmentQuestionPapersIndexRoute =
  AssessmentQuestionPapersIndexImport.update({
    id: '/assessment/question-papers/',
    path: '/assessment/question-papers/',
    getParentRoute: () => rootRoute,
  } as any)

const AssessmentTestsCreateAssessmentIndexRoute =
  AssessmentTestsCreateAssessmentIndexImport.update({
    id: '/assessment/tests/create-assessment/',
    path: '/assessment/tests/create-assessment/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/assessment/question-papers/': {
      id: '/assessment/question-papers/'
      path: '/assessment/question-papers'
      fullPath: '/assessment/question-papers'
      preLoaderRoute: typeof AssessmentQuestionPapersIndexImport
      parentRoute: typeof rootRoute
    }
    '/assessment/tests/': {
      id: '/assessment/tests/'
      path: '/assessment/tests'
      fullPath: '/assessment/tests'
      preLoaderRoute: typeof AssessmentTestsIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/forgot-password/': {
      id: '/login/forgot-password/'
      path: '/login/forgot-password'
      fullPath: '/login/forgot-password'
      preLoaderRoute: typeof LoginForgotPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/students/students-list/': {
      id: '/students/students-list/'
      path: '/students/students-list'
      fullPath: '/students/students-list'
      preLoaderRoute: typeof StudentsStudentsListIndexImport
      parentRoute: typeof rootRoute
    }
    '/assessment/tests/create-assessment/': {
      id: '/assessment/tests/create-assessment/'
      path: '/assessment/tests/create-assessment'
      fullPath: '/assessment/tests/create-assessment'
      preLoaderRoute: typeof AssessmentTestsCreateAssessmentIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/students': typeof StudentsIndexRoute
  '/assessment/question-papers': typeof AssessmentQuestionPapersIndexRoute
  '/assessment/tests': typeof AssessmentTestsIndexRoute
  '/login/forgot-password': typeof LoginForgotPasswordIndexRoute
  '/students/students-list': typeof StudentsStudentsListIndexRoute
  '/assessment/tests/create-assessment': typeof AssessmentTestsCreateAssessmentIndexRoute
}

export interface FileRoutesByTo {
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/students': typeof StudentsIndexRoute
  '/assessment/question-papers': typeof AssessmentQuestionPapersIndexRoute
  '/assessment/tests': typeof AssessmentTestsIndexRoute
  '/login/forgot-password': typeof LoginForgotPasswordIndexRoute
  '/students/students-list': typeof StudentsStudentsListIndexRoute
  '/assessment/tests/create-assessment': typeof AssessmentTestsCreateAssessmentIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/assessment/question-papers/': typeof AssessmentQuestionPapersIndexRoute
  '/assessment/tests/': typeof AssessmentTestsIndexRoute
  '/login/forgot-password/': typeof LoginForgotPasswordIndexRoute
  '/students/students-list/': typeof StudentsStudentsListIndexRoute
  '/assessment/tests/create-assessment/': typeof AssessmentTestsCreateAssessmentIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/students'
    | '/assessment/question-papers'
    | '/assessment/tests'
    | '/login/forgot-password'
    | '/students/students-list'
    | '/assessment/tests/create-assessment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/students'
    | '/assessment/question-papers'
    | '/assessment/tests'
    | '/login/forgot-password'
    | '/students/students-list'
    | '/assessment/tests/create-assessment'
  id:
    | '__root__'
    | '/dashboard/'
    | '/login/'
    | '/students/'
    | '/assessment/question-papers/'
    | '/assessment/tests/'
    | '/login/forgot-password/'
    | '/students/students-list/'
    | '/assessment/tests/create-assessment/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  AssessmentQuestionPapersIndexRoute: typeof AssessmentQuestionPapersIndexRoute
  AssessmentTestsIndexRoute: typeof AssessmentTestsIndexRoute
  LoginForgotPasswordIndexRoute: typeof LoginForgotPasswordIndexRoute
  StudentsStudentsListIndexRoute: typeof StudentsStudentsListIndexRoute
  AssessmentTestsCreateAssessmentIndexRoute: typeof AssessmentTestsCreateAssessmentIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  AssessmentQuestionPapersIndexRoute: AssessmentQuestionPapersIndexRoute,
  AssessmentTestsIndexRoute: AssessmentTestsIndexRoute,
  LoginForgotPasswordIndexRoute: LoginForgotPasswordIndexRoute,
  StudentsStudentsListIndexRoute: StudentsStudentsListIndexRoute,
  AssessmentTestsCreateAssessmentIndexRoute:
    AssessmentTestsCreateAssessmentIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard/",
        "/login/",
        "/students/",
        "/assessment/question-papers/",
        "/assessment/tests/",
        "/login/forgot-password/",
        "/students/students-list/",
        "/assessment/tests/create-assessment/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/students/": {
      "filePath": "students/index.tsx"
    },
    "/assessment/question-papers/": {
      "filePath": "assessment/question-papers/index.tsx"
    },
    "/assessment/tests/": {
      "filePath": "assessment/tests/index.tsx"
    },
    "/login/forgot-password/": {
      "filePath": "login/forgot-password/index.tsx"
    },
    "/students/students-list/": {
      "filePath": "students/students-list/index.tsx"
    },
    "/assessment/tests/create-assessment/": {
      "filePath": "assessment/tests/create-assessment/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
